from os import getenv
from dotenv import load_dotenv
from mssql_python import connect
import pandas as pd

load_dotenv()
conn = connect(getenv("SQL_CONNECTION_STRING"))

SQL_QUERY = """

SELECT 
    CAST (QUANTIDADE AS INT) AS QUANTIDADE,
    CAST (PEDIDO AS NVARCHAR(20)) AS NUM_PEDIDO,
    CAST (TOTAL AS MONEY) AS VALOR_TOTAL,
    CAST (UNITARIO AS MONEY) AS VALOR_UNITARIO,
    CAST (DTPEDIDO AS DATETIME) AS DATA_PEDIDO,
    CAST (LOCAL AS NVARCHAR(50)) AS UNIDADE
    CAST (COD_GRUPO AS NVARCHAR(10)) AS COD_GRUPO
    CAST (CODMATERIAL AS NVARCHAR(20)) AS COD_MATERIAL
    CAST (CODFOR AS NVARCHAR(20)) AS COD_FORNECEDOR
    CAST (CODTDEPESA AS NVARCHAR(20)) AS COD_DESPESA

FROM
    STAGINGPEDIDO_COMPRASCOMPLETO
WHERE
DTPEDIDO > '2025-01-01';

SELECT DISTINCT
    CAST (FORNECEDOR AS NVARCHAR(100)) AS dim.FORNECEDOR
FROM
    STAGINGPEDIDO_COMPRASCOMPLETO;
WHERE
DTPEDIDO > '2025-01-01';    

SELECT DISTINCT
    CAST (MATERIAL AS NVARCHAR(100)) AS dim.MATERIAL
FROM
    STAGINGPEDIDO_COMPRASCOMPLETO;
WHERE
DTPEDIDO > '2025-01-01';    

SELECT DISTINCT
    CAST (GRUPO AS NVARCHAR(100)) AS dim.TIPO_MATERIAL
FROM
    STAGINGPEDIDO_COMPRASCOMPLETO;
WHERE
DTPEDIDO > '2025-01-01';    

SELECT DISTINCT
    CAST (DESPESA AS NVARCHAR(100)) AS dim.DESPESA
FROM
    STAGINGPEDIDO_COMPRASCOMPLETO;
WHERE
DTPEDIDO > '2025-01-01';    

SELECT DISTINCT
    CAST (LOCAL AS NVARCHAR(50)) AS dim.UNIDADE
FROM
    STAGINGPEDIDO_COMPRASCOMPLETO;
WHERE
DTPEDIDO > '2025-01-01';    

LEFT JOIN 
    dim.FORNECEDOR AS d ON 

    
    
"""
cursor = conn.cursor()
cursor.execute(SQL_QUERY)
results = cursor.fetchall()

if results:
    columns = [column[0] for column in cursor.description]
    df = pd.DataFrame(results, columns=columns)
    print(df.head())
else:
    print("No data found.")
