SELECT 
    CAST (QUANTIDADE AS INT) AS QUANTIDADE,
    CAST (PEDIDO AS NVARCHAR(20)) AS NUM_PEDIDO,
    CAST (TOTAL AS MONEY) AS VALOR_TOTAL,
    CAST (UNITARIO AS MONEY) AS VALOR_UNITARIO,
    CAST (DTPEDIDO AS DATETIME) AS DATA_PEDIDO,
    CAST (COD_GRUPO AS NVARCHAR(10)) AS COD_GRUPO_MATERIAL,
    CAST (CODMATERIAL AS NVARCHAR(15)) AS COD_MATERIAL,
    CAST (CODFOR AS NVARCHAR(20)) AS COD_FORNECEDOR,
    CAST (CODTPDESPESA AS NVARCHAR(20)) AS COD_DESPESA,
    CAST (CODLOCAL AS NVARCHAR(20)) AS COD_UNIDADE,
    CAST (EMPRESA AS NVARCHAR(10)) + '-' + CAST (FILIAL AS NVARCHAR(10)) AS COD_EMPRESA

FROM STAGINGPEDIDO_COMPRASCOMPLETO
WHERE DTPEDIDO > '2025-01-01';
 