SELECT 
    CAST (QUANTIDADE AS INT) AS QUANTIDADE,
    CAST (PEDIDO AS NVARCHAR(20)) AS NUM_PEDIDO,
    CAST (TOTAL AS MONEY) AS VALOR_TOTAL,
    CAST (UNITARIO AS MONEY) AS VALOR_UNITARIO,
    CAST (DTPEDIDO AS DATETIME) AS DATA_PEDIDO,
    CAST (LOCAL AS NVARCHAR(50)) AS UNIDADE,
    CAST (COD_GRUPO AS NVARCHAR(10)) AS COD_GRUPO_MATERIAL,
    LEFT (CAST (CODMATERIAL AS NVARCHAR(4)), 4) AS COD_MATERIAL,
    CAST (CODFOR AS NVARCHAR(20)) AS COD_FORNECEDOR,
    CAST (CODTPDESPESA AS NVARCHAR(20)) AS COD_DESPESA
FROM STAGINGPEDIDO_COMPRASCOMPLETO
WHERE DTPEDIDO > '2025-01-01';
 