SELECT DISTINCT
    CAST (DIM_EMPRESA_FILIAL.CODIGOEMPRESA AS NVARCHAR(10)) + '-' + 
    CAST (DIM_EMPRESA_FILIAL.CODIGOFL AS NVARCHAR(10)) + '-' + 
    CAST(DIM_CadLocal.CODIGOLOCAL AS NVARCHAR(10)) AS COD_TOTAL,

    CAST (RSOCIALEMPRESA AS NVARCHAR(100)) AS NOME_EMPRESA,

    DESCRICAOLOCAL
    
FROM 
    DIM_CadLocal
LEFT JOIN 
    DIM_EMPRESA_FILIAL ON DIM_CadLocal.CODIGOEMPRESA = DIM_EMPRESA_FILIAL.CODIGOEMPRESA

    AND DIM_CadLocal.CODIGOFL = DIM_EMPRESA_FILIAL.CODIGOFL
WHERE NOT
    DIM_EMPRESA_FILIAL.RSOCIALEMPRESA = 'xyz'
    AND NOT
    DIM_EMPRESA_FILIAL.RSOCIALEMPRESA = 'xyz';