SELECT DISTINCT
    CAST (MATERIAL AS NVARCHAR(100)) AS DESCRICAO_MATERIAL,
    CAST (CODMATERIAL AS NVARCHAR(10)) AS COD_MATERIAL
FROM  STAGINGPEDIDO_COMPRASCOMPLETO
WHERE DTPEDIDO > '2025-01-01';    