SELECT 
    CAST (QUANTIDADE AS INT) AS QUANTIDADE,
    CAST (PEDIDO AS NVARCHAR(20)) AS NUM_PEDIDO,
    CAST (GRUPO AS NVARCHAR(20)) AS TIPO_MATERIAL,
    CAST (TOTAL AS MONEY) AS VALOR_TOTAL,
    CAST (UNITARIO AS MONEY) AS VALOR_UNITARIO,
    CAST (DTPEDIDO AS DATETIME) AS DATA_PEDIDO,
    
    MATERIAL,
    DESPESA,
    LOCAL

FROM
    STAGINGPEDIDO_COMPRASCOMPLETO
WHERE
DTPEDIDO > '2025-01-01';

SELECT DISTINCT
    CAST (DESPESA AS NVARCHAR(100)) AS DESPESA
FROM
    STAGINGPEDIDO_COMPRASCOMPLETO;